[package]
name = "feedme-manual"
version = "0.1.1"
edition = "2021"
authors = ["KizzyCode Software Labs./Keziah Biermann <development@kizzycode.de>"]
keywords = []
categories = []
description = "Canonicalizes the metadata from a yt-dlp playlist for further use with FeedMe"
license = "BSD-2-Clause OR MIT"
repository = "https://github.com/KizzyCode/FeedMe-rust"
readme = "README.md"


[[bin]]
name = "feedme-manual"
path = "src/main.rs"


[badges]
appveyor = { repository = "KizzyCode/FeedMe-rust" }


[features]
default = []


[dependencies]
feedme-shared = { version = "0.1.0", path = "../shared" }
serde = { version = "1.0.152", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1.0.91", default-features = false, features = ["std"] }

[target."cfg(unix)".dependencies]
libc = { version = "0.2.139", default-features = false }


[profile.release]
overflow-checks = true

[profile.bench]
overflow-checks = true
